name: PayloadGuard Analysis
on:
  pull_request:
    branches: [ main ]

jobs:
  forensic-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # Pinned to v4.1.1 (Full 40-character SHA)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: PayloadGuard
        # Pinned to the verified commit SHA
        uses: PayloadGuard-PLG/payload-consequence-analyser@2bbd0c77c28dcd75548d4b933911f29028c91847
        with:
          analysis_depth: 'forensic'
          fail_on_risky_diff: true
